language: node_js
node_js:
  - 'stable'
sudo: true
dist: trusty

cache:
  directories:
    - node_modules

before_script:
 - export CHROME_BIN=/usr/bin/google-chrome
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start
 - sudo apt-get update
 - sudo apt-get install -y libappindicator1 fonts-liberation
 - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
 - sudo dpkg -i google-chrome*.deb

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install

jobs:
  include:
    - stage: lint
      script:
        - ng lint
    - stage: test
      script:
        - npm run test:lib-coverage
        - npm run report-coverage:lib
    - stage: build & publish showcase
      script:
        - npm run build:demo
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GH_TOKEN
        local_dir: dist/demo
      if: branch = master
    - stage: build & publish lib
      script:
        - npm run build:lib
        - npm run publish:lib
      if: branch = master