sudo: required
addons:
  chrome: stable
language: node_js
node_js:
  - '14.19.3'
dist: trusty

cache:
  directories:
    - node_modules

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install -g yarn
  - yarn install

jobs:
  include:
    - stage: lint
      script:
        - yarn lint:lib
    - stage: test
      script:
        - yarn test:lib-coverage
        - yarn report-coverage:lib
    - stage: build & publish showcase
      script:
        - yarn build:demo
      deploy:
        provider: pages
        skip_cleanup: true
        token: $GH_TOKEN
        local_dir: dist/demo
        keep_history: true
      if: branch = master
    - stage: build & publish lib
      script:
        - yarn build:lib
        - yarn publish:lib
      if: branch = master
